
// This file was generated by Firebase Studio
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "studio-8440360269-51cd3",
  "appId": "1:471938808893:web:2a5d21d50dc194d3f8fe54",
  "apiKey": "AIzaSyBqc6dkyV3USUVaGifwwULQ2g9-rZCL3RU",
  "authDomain": "studio-8440360269-51cd3.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "471938808893"
};

function createFirebaseApp(config: any) {
  const app = initializeApp(config);
  return app;
}

function getFirebaseApp() {
  if (getApps().length) {
    return getApp();
  }

  if (!firebaseConfig) {
    throw new Error('No Firebase config object provided.');
  }

  const app = createFirebaseApp(firebaseConfig);
  return app;
}

export const app = getFirebaseApp();
export const auth = getAuth(app);
export const db = getFirestore(app);
