
// This file was generated by Firebase Studio
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "studio-8440360269-51cd3",
  "appId": "1:471938808893:web:2a5d21d50dc194d3f8fe54",
  "apiKey": "AIzaSyBqc6dkyV3USUVaGifwwULQ2g9-rZCL3RU",
  "authDomain": "studio-8440360269-51cd3.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "471938808893"
};

const app = getApps().length ? getApp() : initializeApp(firebaseConfig);

export const auth = getAuth(app);
export const db = getFirestore(app);
