// This file was generated by Firebase Studio
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';

const firebaseConfig = null;

function createFirebaseApp(config: any) {
  const app = initializeApp(config);
  return app;
}

function getFirebaseApp() {
  if (getApps().length) {
    return getApp();
  }

  if (!firebaseConfig) {
    throw new Error('No Firebase config object provided.');
  }

  const app = createFirebaseApp(firebaseConfig);
  return app;
}

export const app = getFirebaseApp();
export const auth = getAuth(app);
export const db = getFirestore(app);
